### ISSUE TITLE
check that there are no duplicates in job-mapping

### ISSUE THREAD

**Issue by robstoll** [loewenfels/dep-graph-releaser#14]
We currently allow duplicates in job-mapping. This is surely a minor issue but it would be handy nonetheless if we get a warning or maybe even better an error in case there are duplicates.

The error should be shown when we use the Json console command (additional input check in parseJobMapping). A bonus would be, if the user also gets an error if he tries to save an invalid configuration.

**Comment by schereradi** [comment]
What do you mean with a duplicate? A duplicate in the mapped job (case 1), a duplicate in the project (case 2) oder a duplicate in the whole mapping (case 3)?

**Case 1:**
com:job1=job-1,com:job2=job-1

**Case 2:**
com:job1=job-1,com:job1=job-2

**Case 3:**
com:job1=job-1,com:job1=job-1

**Comment by robstoll** [comment]
I meant case 2. We have currently a `first wins` strategy implemented. Which means, if the user has a long job-mapping list and adds another one at the end which was already added, then it does not work as the user expects.
