### ISSUE TITLE
Clicking disabled buttons

### ISSUE THREAD

**Issue by kayth1** [loewenfels/dep-graph-releaser#43]
While there are still some jobs running, the ui doesn't allow clicking any buttons on failed jobs, e.g. "set command to succeeded". But it just pretends so, you are still able to click this buttons.

**Comment by robstoll** [comment]
Thanks for the bug report :+1: , would you like to be included in the contributors table with your profile picture and link to you profile (contributor table is coming soon)? We value all contributions from feedback over bug reports to fixes :slightly_smiling_face:
