### ISSUE TITLE
Build failed need to specify mvnId with -pmvnIds

### ISSUE THREAD

**Issue by aarengee** [loewenfels/dep-graph-releaser#82]

**Comment by robstoll** [comment]
Sorry, the wiki was not up to date. I guess you tried to run dep-graph-releaser locally. Have a look at the wiki again: https://github.com/loewenfels/dep-graph-releaser/wiki/Local-Usage

**Comment by robstoll** [comment]
I guess the problem is resolved otherwise let us know
