### ISSUE TITLE
renew sonar API token and re-activate sonar in build

### ISSUE THREAD

**Issue by robstoll** [loewenfels/dep-graph-releaser#83]
TODO:
- go to sonarcloud.io, log in as user with admin rights for loewenfels. 
- create a new API token https://sonarcloud.io/documentation/user-guide/user-token/ 
- change the Token in travis -> https://travis-ci.org/loewenfels/dep-graph-releaser/settings
- uncomment TODO in .travis.yml

**Comment by robstoll** [comment]
If I were you, then I would change the badge in addition, it points to loewenfels (btw. in case you created a new org due to missing access, Lukas should have access)

**Comment by schereradi** [comment]
@robstoll I've already changed it in commit a53b9ed10973813c6bb6097aefdabd71e0a820ac. 👍 I don't know why I had to create a new org but the old just didn't work... 
Now I'm struggling with the code coverage... 😅
