### ISSUE TITLE
empty jobmapping not supported

### ISSUE THREAD

**Issue by subes** [loewenfels/dep-graph-releaser#87]
As discussed here: https://github.com/loewenfels/dep-graph-releaser/issues/84#issuecomment-505809858

This happens when no projects have a ciManagement tag and no jobMapping is provided. The dgr page halts at "Loading release.json..." and shows the below error.

```
IllegalArgumentException: At least one mapping has no groupId and artifactId defined.
jobMapping:

  Exception@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/kotlin.js:24805:14
  RuntimeException@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/kotlin.js:24840:17
  IllegalArgumentException@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/kotlin.js:24860:24
  IllegalArgumentException_init_0@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/kotlin.js:24871:32
  parseJobMapping_0@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-api-js.js?v=1.2.0:266:15
  parseJobMapping@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-api-js.js?v=1.2.0:245:12
  ReleaseJobExecutionDataFactory@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-gui.js?v=1.2.0:5733:25
  ModifiableState.prototype.initJsonDependentFields_0@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-gui.js?v=1.2.0:6731:46
  ModifiableState@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-gui.js?v=1.2.0:6665:10
  App$start$lambda$lambda/<@https://invesdwin.de/jenkins/userContent/dep-graph-releaser/dep-graph-releaser-gui.js?v=1.2.0:1037:29
```

**Comment by robstoll** [comment]
could you please share the generated release.json (or at least the config section)

**Comment by subes** [comment]
This is the json output (here with just once module as an example, but the same error occurred when I had multiple in the dgr-analyse):

`{"releaseId":"f013a93b1efd4d0","state":"READY","typeOfRun":"EXPLORE","id":{"t":"MavenProjectId","p":{"groupId":"de.invesdwin","artifactId":"invesdwin-bom"}},"projects":[{"id":{"t":"MavenProjectId","p":{"groupId":"de.invesdwin","artifactId":"invesdwin-bom"}},"isSubmodule":false,"currentVersion":"1.0.6-SNAPSHOT","releaseVersion":"1.0.6","level":0,"commands":[{"t":"JenkinsSingleMavenRelease","p":{"state":{"state":"READY"},"nextDevVersion":"1.0.7-SNAPSHOT"}}],"relativePath":"invesdwin-bom/invesdwin-bom/"}],"submodules":[{"k":{"t":"MavenProjectId","p":{"groupId":"de.invesdwin","artifactId":"invesdwin-bom"}},"v":[]}],"dependents":[{"k":{"t":"MavenProjectId","p":{"groupId":"de.invesdwin","artifactId":"invesdwin-bom"}},"v":[]}],"warnings":[],"infos":[],"config":[["commitPrefix","[DGR]"],["updateDependencyJob","dgr-update"],["dryRunJob","dgr-dryrun"],["remoteRegex",".*#https://invesdwin.de/jenkins"],["relativePathExcludeProjectsRegex",".*"],["relativePathToGitRepoRegex","^(.*)/$"],["relativePathToGitRepoReplacement","https://github.com/subes/$1\\.git"],["regexParams",""],["jobMapping",""],["buildWithParamJobs",""],["initialJson",""]]}`

**Comment by robstoll** [comment]
Thanks, at first glance this seems to be good and should work. Let's hope someone of Löwenfels takes a look at this and fixes it. In case you need this urgently then you can contact me by email

**Comment by subes** [comment]
Thanks, though I found enough workarounds for me to make everything work currently. The topics we are discussing are just things that might help future adopters and might provide simplifications that I can integrate into my setup at a later stage. For now I am able to make releases. :) So still thanks a lot for this amazing tool!
