### ISSUE TITLE
let dependabot manage dependencies

### ISSUE THREAD

**Issue by robstoll** [loewenfels/dep-graph-releaser#96]
@schereradi I have already created a request to include dependabot in this repo. I have tried out dependabot myself for different kotlin projects and it worked fine and I though maybe you are interested in it as well. It basically scans the project on a regular basis and creates pull requests in case there is a newer version out there.

**Comment by schereradi** [comment]
Sounds interesting, thanks for sharing your experience. 
So you've already signed up and granted access to this repo, right? We can commit now a `.dependabot/config.yml` file and let dependabot start working?

**Comment by robstoll** [comment]
Nope, I only requested rights at the loewenfels organisation as I cannot longer give rights (maybe the corresponding email was sent to info@loewenfels.ch?) You would need to give the rights. Alternatively you could go to dependabot.com and give the rights there. There is no config needed. It is generally enough if you activate dependabot for this particular repo there

**Comment by schereradi** [comment]
Access granted for Dependabot to this repo.

**Comment by robstoll** [comment]
:+1: I hope it helps to keep dependencies up-to-date
